# Generated by Django 5.2.7 on 2025-10-14 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_remove_order_product_remove_order_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('in transit', 'In Transit'), ('canceled', 'Canceled')], default='pending', max_length=20),
        ),
    ]
